### ISSUE TITLE
Help with playlists

### ISSUE THREAD

**Issue by AndyM48** [CogentRedTester/mpv-coverart#6]
I see that there is support for cover art embedded in a playlist, but I am not sure how this works.

My playlist looks like this:

```
#EXTM3U
#EXTINF:-1 BBC Radio 1
#EXTIMG: radio1.jpg
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_one/bbc_radio_one.isml/bbc_radio_one-audio%3d48000.norewind.m3u8
#EXTINF:-1 BBC Radio 2
#EXTIMG: radio2.jpg
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_rwo/bbc_radio_two.isml/bbc_radio_two-audio%3d48000.norewind.m3u8
```
but the cover art is not shown in mpv.

Can you please help me out with this?

**Comment by AndyM48** [comment]
So it seems that mpv does not understand anything in a playlist except #EXTINF: and the correct format is
 
`#EXTINF:length,title`

Coverart will use a valid cover art file included in the playlist, for the whole list.

There are references to icy files in the configuration settings but I do not know how or if, these work with the above urls.

**Comment by CogentRedTester** [comment]
The icy settings allow you to specify coverart based on the icy_name metadata field on the stream. However, it does not look like your streams there set the icy_name field. So there is no way for this script to detect the coverart automatically. You can probably set some manual coverart loading rules with [conditional auto profiles](https://mpv.io/manual/master/#conditional-auto-profiles) though. I'll look into this and get back to you.

**Comment by AndyM48** [comment]
Thank you

**Comment by CogentRedTester** [comment]
You should be able to create a simple auto-profile like this:

```properties
[radio1]
profile-cond= path == "http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_one/bbc_radio_one.isml/bbc_radio_one-audio%3d48000.norewind.m3u8"
profile-restore=copy
cover-art-files-append="/path/to/file"
```
